version: '3.3'

services:
   db:
     image: mariadb:latest
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: 1qazXSW21
       MYSQL_DATABASE: webapp
       MYSQL_USER: dbuser
       MYSQL_PASSWORD: 1qazXSW2
   app:
     depends_on:
       - db
     image: vipinmadhav90/webapp:5.0
     ports:
       - "80:8080"
     restart: always
     environment:
       APP_DB_HOST: db
       APP_DB_NAME: webapp
       APP_DB_USER: dbuser
       APP_DB_PASSWORD: 1qazXSW2
volumes:
   db_data: {}
